stages:
  - build
  - push

build_image:
  stage: build
  tags:
    - docker_build
  script:
    - docker build -t git5.zswap.net:5050/nathan/build-ahoy .


push_image:
  stage: push
  tags:
    - docker_build
  script:
    - docker push git5.zswap.net:5050/nathan/build-ahoy

